project_name: drprune
env:
  - GO111MODULE=on
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: drprune
    binary: drprune
    env:
      - CGO_ENABLED=0
    main: ./cmd/drprune/main.go
    goos:
      - linux
      - windows
      - darwin
    mod_timestamp: '{{.CommitTimestamp}}'
    flags:
      - -trimpath
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
snapshot:
  name_template: 'SNAPSHOT-{{ .Commit }}'
checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256
changelog:
  skip: true
